### ISSUE TITLE
ubl4nk - Use safeTransferFrom instead of transferFrom

### ISSUE THREAD

**Issue by sherlock-admin2** [sherlock-audit/2024-01-telcoin-judging#21]
ubl4nk

medium

# Use safeTransferFrom instead of transferFrom

## Summary
The transferFrom() function returns a boolean value indicating success. This parameter needs to be checked to see if the transfer has been successful.

## Vulnerability Detail
Some tokens like [EURS](https://etherscan.io/address/0xdb25f211ab05b1c97d595516f45794528a807ad8#code) and [BAT](https://etherscan.io/address/0x0d8775f648430679a709e98d2b0cb6250d2887ef#code) will not revert if the transfer failed but return false instead.
So if the `rewardToken` is one of these tokens, the return value is not checked:
```solidity
function topUp(
        address source,
        uint256[] memory indices
    ) external onlyRole(EXECUTOR_ROLE) {
        for (uint i = 0; i < indices.length; i++) {
            // get staking contract and config
            StakingRewards staking = stakingContracts[i];
            StakingConfig memory config = stakingConfigs[staking];

            // will revert if block.timestamp <= periodFinish
            staking.setRewardsDuration(config.rewardsDuration);

            // pull tokens from owner of this contract to fund the staking contract
            rewardToken.transferFrom(
                source,
                address(staking),
                config.rewardAmount
            );

            // start periods
            staking.notifyRewardAmount(config. rewardAmount);

            emit ToppedUp(staking, config);
        }
    }
```

Do to that the `notifyRewardAmount` is called just after `transferFrom` and `StakingRewards` is out-of-scope, so any accounting/protcol-update which has not considered `false`-transfers inside the `notifyRewardAmount`, will cause major problems for the protocol.

## Impact
Any update/accounting inside the `notifyRewardAmount` without considering `false`-transfers, will cause major problems for the protocol.

## Code Snippet

https://github.com/sherlock-audit/2024-01-telcoin/blob/0954297f4fefac82d45a79c73f3a4b8eb25f10e9/telcoin-audit/contracts/telx/core/StakingRewardsManager.sol#L254-L278

## Tool used

Manual Review

## Recommendation
Use OZ’s SafeERC20’s safeTransferFrom() function.

Duplicate of #8

**Comment by Alireza-Razavi** [comment]
Escalate
I believe this is a valid medium due to that the issue is many many times accepted a Medium by Sherlock.
Examples:
https://github.com/sherlock-audit/2022-11-dodo-judging/issues/47
https://github.com/sherlock-audit/2023-01-cooler-judging/issues/39
Also due to that the `staking.notifyRewardAmount` is out-of-scope, so the auditors are unaware of what will happen inside `notifyRewardAmount` and they are just reported the issue based on the README and Scope.

**Comment by Alireza-Razavi** [comment]
if we assume rewardToken is TEL:
- TEL implementation is not in scope, so we don't know what is inside it.
- `notifyRewardAmount` is also out-of-scope and we don't know what is the actual StakingContract and what will be inside it, due to the sponsor message in discord, the StakingContract in the repo is not the actual contract and they will use another StakingReward/StakingContract.
- rewardToken is exactly part of the core business logic, so the auditors have reported this issue only based on the scope.
- Based on the README, the auditors don't know which contracts will be deployed on which chains

So finally i want to say again: the watsons are reported this issue only based on the SCOPE and the README.
Much respects to the judge's decisions.
@Czar102 @nevillehuang

**Comment by nevillehuang** [comment]
I have no further comments or this issue, I believe [this](https://github.com/sherlock-audit/2024-01-telcoin-judging/issues/8#issuecomment-1915400612) is sufficient. The watson argument for out-of-scope and "not known" logic is not a valid reason to validate the issue, because the fact is there is no issue.  This should remain as invalid.

**Comment by amshirif** [comment]
Duplicate https://github.com/telcoin/telcoin-audit/pull/25

**Comment by Alireza-Razavi** [comment]
@nevillehuang @Czar102 
We just considered the README and the SCOPE.

Please look at the report from the auditor's view:
- Auditor was not aware of TEL implementation and rewardToken implementation.
- Auditor was not aware of `notifyRewardAmount` implementation due to that the StakingContract was out-of-scope.
- Auditor was not aware of what contract will be deployed on which chains.

There just mentioned that non-Standard tokens are not supported -> this doesn't include the rewardToken, because it is as the core part of business logic, take a look at this line:
https://github.com/sherlock-audit/2024-01-telcoin/blob/0954297f4fefac82d45a79c73f3a4b8eb25f10e9/telcoin-audit/contracts/protocol/core/TelcoinDistributor.sol#L193
if TEL is standard-token, why here they are using `safeTransferFrom` for it ? by looking at this line, auditors think that it might be a non-standard and decide to report it (also consider that the TEL implementation itself is not included in the scope).

**Comment by Evert0x** [comment]
The protocol teams answer NO to the following question in the REAMDE
> Do you expect to use any of the following tokens with non-standard behaviour with the smart contracts?

https://github.com/d-xo/weird-erc20

For this reason, planning to invalidate issue.

**Comment by Alireza-Razavi** [comment]
@Evert0x 
But still i believe Non-Standard here doesn't include the TEL and rewardToken.

Why they have used `safeTransferFrom` for TEL if it is a standard-token ? you say it won't be a non-standard-token, how the auditor should  detect it when it is not included in the scope ?
When the auditor sees that there are used `safeTransferFrom` for TEL, then the auditor thinks that it might be a non-standard. 

Here they are used `safeTransferFrom` for TELCOIN:
https://github.com/sherlock-audit/2024-01-telcoin/blob/0954297f4fefac82d45a79c73f3a4b8eb25f10e9/telcoin-audit/contracts/protocol/core/TelcoinDistributor.sol#L193

**Comment by Evert0x** [comment]
> Why they have used safeTransferFrom for TEL if it is a standard-token ?

`safeTransferFrom` works for both standard and non-standard tokens. 

> you say it won't be a non-standard-token, how the auditor should detect it when it is not included in the scope ?

Based on the Q&A on the contest page

> When the auditor sees that there are used safeTransferFrom for TEL, then the auditor thinks that it might be a non-standard.

Always use the Q&A as the source of truth

Still planning to invalidate issue.

**Comment by Evert0x** [comment]
Result:
Invalid
Duplicate of #8

**Comment by sherlock-admin** [comment]
Escalations have been resolved successfully!

Escalation status:
- [alireza-razavi](https://github.com/sherlock-audit/2024-01-telcoin-judging/issues/21/#issuecomment-1915373457): rejected

**Comment by sherlock-admin** [comment]
The protocol team fixed this issue in PR/commit https://github.com/telcoin/telcoin-audit/pull/25.

**Comment by sherlock-admin** [comment]
The Lead Senior Watson signed-off on the fix.
